### ISSUE TITLE
Minimum Target iOS 13 since v6.0.0, but can be compiled on project with min iOS 12.2

### ISSUE THREAD

**Issue by rickirby** [talsec/Free-RASP-iOS#16]
Hi, I see that since [version 6.0.0](https://github.com/talsec/Free-RASP-iOS/releases/tag/v6.0.0), the minimum iOS deployment target is increased to be `13.0`.<br>
But currently my project still support iOS `12.2`. I try to use latest version (`6.4.0`) and my project can be compiled and run well.<br>
Is there any issue if I go forward to use 6.4.0 for my project that still support iOS 12.2?

**Comment by msikyna** [comment]
Hello @rickirby ,
due to internal refactoring and new features, the deployment target has been increased since the 6.0.0.

It is advisable to increase the deployment target to at least 13.0. We cannot guarantee that it will be working on 12.2. In fact, none of the data from the versions higher than 6.0.0 contain the OS version less than 13.0.

Is there a specific reason why are you supporting from 12.2? The current iOS is 17 and soon, the 18 will be released. Our data from freeRASP show that approximatelly 0.13% of devices have the iOS version less than 13.

Kind regards,
Talsec team

**Comment by rickirby** [comment]
Hi, thanks for your response.

> We cannot guarantee that it will be working on 12.2.

Yes you're right. Even my project (that consume Talsec Free-RASP `6.4.0`) can be compiled successfully for a project config which still support iOS 12.2, but it will crash on Runtime if I deploy the binary into a real device running iOS 12.2.

Thank you, and this issue can be closed
